### PR TITLE
fix(un_wpp): Explorer pointing to the wrong files

### PR DESCRIPTION
**Pull request by lucasrodes**
The explorer was not showing any data for metrics `Child mortality rate` and `Infant mortality rate`. These occurred because the Explorer was trying to read from an inexistent file.

More context in https://github.com/owid/owid-issues/issues/586

### CODE REVIEW

**Review by larsyencken — CHANGES_REQUESTED** [review]
The top of this file contains:

```
# DO NOT EDIT THIS FILE BY HAND. It is automatically generated using a set of input files. Any changes made directly to it will be overwritten.
```

Is it possible to update the generating script somehow?

**Comment by lucasrodes** [comment]
Hi @lars, I updated the configuration used in the script (file `scripts/demography-explorer/metrics.csv`). Once pushed, the file `explorers/population-and-demography.explorer.tsv` was automatically updated by an automated workflow.

**Review by larsyencken — APPROVED** [review]
Thanks Lucas. Tested it also myself locally, it appears to fix the issue 👍 

Ship it! :shipit:

**Comment by lucasrodes** [comment]
@larsyencken I am not sure if this fix is why we got a sudden peak in visits in our population-demography explorer.

But so far is the only thing I found that correlates with this chart: https://datastudio.google.com/reporting/5a1e775a-b399-4d91-baad-bb41516eb5a4

**Review by marcelgerber — COMMENTED** [review]
Looking good, thank you lucas!

**Pull request merged**
